version: '3.1'

services:

  db:
    container_name: postgres_container
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: daniel.martinezgarcia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8085:80"      
    networks:
      - postgres 
    depends_on:
      - db


networks:
  postgres:
    driver: bridge